Feature/3 ci cd
yevhen-komarov/dg-basic-react pull request #3
Opened 2022-05-19 09:47 UTC by yevhen-komarov

Изучение, настройка и тестирование GitHub Actions и GitHub Pages.
GitHub Pages: https://yevhen-komarov.github.io/dg-basic-react/

2022-05-19 10:14 UTC, mmospanenko requested changes
I think you simply copied and paste this from somewhere, you should get new knowledge, not just working result. And you have warnings - need to fix them all

2022-05-19 10:14 UTC, mmospanenko commented on .github/workflows/develop-tests.yml
> +      - run: npm ci
why npm when we're using yarn?

2022-05-19 10:14 UTC, mmospanenko commented on .github/workflows/develop-tests.yml
> +          node-version: ${{ matrix.node-version }}
matrix? We don't need multiple versions to test with

2022-05-19 10:14 UTC, mmospanenko commented on .github/workflows/develop-tests.yml
> +        node-version: [16.x]
use more specific version definitions

2022-05-19 10:14 UTC, mmospanenko commented on package.json
> +    "build-gh-pages": "tsc && vite build --base=/dg-basic-react/",
why not build? it is ok to have only one build destination for now

2022-05-22 08:34 UTC, yevhen-komarov commented on .github/workflows/develop-tests.yml
> +      - run: npm ci
fixed

2022-05-22 08:34 UTC, yevhen-komarov commented on .github/workflows/develop-tests.yml
> +          node-version: ${{ matrix.node-version }}
fixed

2022-05-22 08:34 UTC, yevhen-komarov commented on .github/workflows/develop-tests.yml
> +        node-version: [16.x]
fixed

2022-05-23 15:16 UTC, mmospanenko approved these changes
approved, added some comments/questions

2022-05-23 16:14 UTC, yevhen-komarov commented on package.json
> +    "build-gh-pages": "tsc && vite build --base=/dg-basic-react/",
not needed, removed tsc from scripts

2022-05-23 16:15 UTC, merged